# Generated by Django 5.2.4 on 2025-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_itemcarrito_fecha_agregado_not_null'),
        ('catalogo', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
        migrations.AddField(
            model_name='carrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='subtotal',
        ),
    ]
