# Generated by Django 5.2.8 on 2025-11-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_alter_itemcarrito_unique_together_carrito_activo_and_more'),
        ('catalogo', '0007_producto_sexo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante específica del producto seleccionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='catalogo.productovariante'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'variante')},
        ),
    ]
