# Generated by Django 5.2.8 on 2025-11-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='nombre_producto',
        ),
    ]
