# Generated by Django 5.2.8 on 2025-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_itempedido_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
