# Generated by Django 5.2.8 on 2025-11-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_historialestadopedido_comentario_pedido_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_preparacion', max_length=20),
        ),
    ]
