# Generated by Django 5.2.8 on 2025-11-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_sexo'),
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante específica del producto seleccionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='catalogo.productovariante'),
        ),
    ]
