# Generated by Django 5.2.8 on 2025-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_itempedido_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado del pago del pedido', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo en local'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='mercadopago', help_text='Método de pago utilizado', max_length=20),
        ),
    ]
