# Generated by Django 5.2.4 on 2025-11-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
