# Generated by Django 5.2.4 on 2025-11-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversación de Chatbot',
                'verbose_name_plural': 'Conversaciones de Chatbot',
                'db_table': 'chatbot_conversaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Chatbot',
                'verbose_name_plural': 'Mensajes de Chatbot',
                'db_table': 'chatbot_mensajes',
                'ordering': ['fecha_mensaje'],
            },
        ),
    ]
