# Generated by Django 5.2.8 on 2025-11-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotmensaje',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='chatbotmensaje',
            name='producto_relacionado',
        ),
        migrations.DeleteModel(
            name='ChatbotConversacion',
        ),
        migrations.DeleteModel(
            name='ChatbotMensaje',
        ),
    ]
