# Generated by Django 5.2.8 on 2025-11-12 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(blank=True, help_text='Código hexadecimal del color (ej: #FF5733)', max_length=7, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'tallas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio base del producto', max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, help_text='Código único de la variante', max_length=100, null=True, unique=True)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio adicional para esta variante (puede ser 0)', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogo.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogo.talla')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'productos_variantes',
                'ordering': ['producto', 'talla', 'color'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(related_name='productos', through='catalogo.ProductoVariante', to='catalogo.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(related_name='productos', through='catalogo.ProductoVariante', to='catalogo.talla'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['producto', 'talla', 'color'], name='productos_v_product_ecf8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['sku'], name='productos_v_sku_119aa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'talla', 'color')},
        ),
    ]
