# Generated by Django 5.2.8 on 2025-11-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_color_talla_remove_producto_color_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productovariante',
            name='productos_v_sku_119aa4_idx',
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='precio_adicional',
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='sku',
        ),
    ]
