# Generated by Django 5.2.8 on 2025-11-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_productovariante_productos_v_sku_119aa4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, esta imagen pertenece específicamente a esta variante. Si es NULL, es una imagen general del producto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.productovariante'),
        ),
    ]
