# Generated by Django 5.2.8 on 2025-11-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_imagenproducto_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Sexo del producto (M: Masculino, F: Femenino)', max_length=1, null=True),
        ),
    ]
