# Generated by Django 5.2.7 on 2025-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_estado_pago'),
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.IntegerField(default=1, help_text='Cantidad de cuotas'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='merchant_order_id',
            field=models.CharField(blank=True, help_text='ID de orden del comerciante', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='payer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='payer_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID de pago de MercadoPago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='preference_id',
            field=models.CharField(blank=True, help_text='ID de preferencia de MercadoPago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='status_detail',
            field=models.CharField(blank=True, help_text='Detalle del estado del pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(blank=True, help_text='Tipo de pago (credit_card, debit_card, ticket, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('en_proceso', 'En Proceso'), ('en_mediacion', 'En Mediación'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('mercadopago', 'MercadoPago'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria')], default='mercadopago', max_length=100),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['preference_id'], name='pagos_prefere_ba28c0_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['payment_id'], name='pagos_payment_7d7acd_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado_pago'], name='pagos_estado__8ffe11_idx'),
        ),
    ]
