# Generated by Django 5.2.8 on 2025-11-08 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_categoria_descripcion'),
        ('pedidos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Activar/desactivar integración con Google Analytics')),
                ('property_id', models.CharField(blank=True, help_text='ID de la propiedad de GA4 (ej: G-XXXXXXXXXX)', max_length=100, null=True)),
                ('credenciales_json', models.TextField(blank=True, help_text='JSON de credenciales de servicio de Google (mantener privado)', null=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, help_text='Última vez que se sincronizaron datos', null=True)),
                ('error_ultimo', models.TextField(blank=True, help_text='Último error en la sincronización', null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Google Analytics',
                'verbose_name_plural': 'Configuración de Google Analytics',
                'db_table': 'analytics_config_google',
            },
        ),
        migrations.CreateModel(
            name='MetricaProducto',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metricas', serialize=False, to='catalogo.producto')),
                ('vistas_totales', models.IntegerField(default=0)),
                ('vistas_ultimos_7d', models.IntegerField(default=0)),
                ('vistas_ultimos_30d', models.IntegerField(default=0)),
                ('agregados_carrito', models.IntegerField(default=0, help_text='Total de veces agregado al carrito')),
                ('compras_completadas', models.IntegerField(default=0, help_text='Total de unidades vendidas')),
                ('tasa_conversion', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de conversión (compras/vistas)', max_digits=5)),
                ('ingreso_generado', models.DecimalField(decimal_places=2, default=0, help_text='Ingreso total generado por el producto', max_digits=12)),
                ('stock_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Promedio histórico de stock', max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Producto',
                'verbose_name_plural': 'Métricas de Productos',
                'db_table': 'analytics_metricas_producto',
            },
        ),
        migrations.CreateModel(
            name='DatosGoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('sesiones', models.IntegerField(default=0)),
                ('usuarios', models.IntegerField(default=0)),
                ('paginas_vistas', models.IntegerField(default=0)),
                ('tasa_rebote', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de rebote', max_digits=5)),
                ('duracion_promedio', models.IntegerField(default=0, help_text='Duración promedio de sesión en segundos')),
                ('trafico_organico', models.IntegerField(default=0)),
                ('trafico_directo', models.IntegerField(default=0)),
                ('trafico_social', models.IntegerField(default=0)),
                ('trafico_referido', models.IntegerField(default=0)),
                ('desktop', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
                ('tablet', models.IntegerField(default=0)),
                ('paginas_populares', models.JSONField(blank=True, default=list, help_text='Lista de páginas más visitadas con contadores')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Datos de Google Analytics',
                'verbose_name_plural': 'Datos de Google Analytics',
                'db_table': 'analytics_datos_google',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('pedidos_totales', models.IntegerField(default=0)),
                ('pedidos_completados', models.IntegerField(default=0)),
                ('ingreso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_neto', models.DecimalField(decimal_places=2, default=0, help_text='Después de costos de envío', max_digits=12)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Valor promedio por pedido', max_digits=10)),
                ('usuarios_nuevos', models.IntegerField(default=0)),
                ('usuarios_activos', models.IntegerField(default=0, help_text='Usuarios que realizaron alguna acción')),
                ('sesiones_totales', models.IntegerField(default=0)),
                ('carritos_creados', models.IntegerField(default=0)),
                ('carritos_abandonados', models.IntegerField(default=0)),
                ('tasa_abandono', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de carritos abandonados', max_digits=5)),
                ('tasa_conversion', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de conversión de visita a compra', max_digits=5)),
                ('productos_vendidos', models.IntegerField(default=0, help_text='Total de unidades vendidas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria_mas_vendida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_mas_vendida', to='catalogo.categoria')),
                ('producto_mas_vendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_mas_vendido', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Métrica Diaria',
                'verbose_name_plural': 'Métricas Diarias',
                'db_table': 'analytics_metricas_diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(choices=[('vista_producto', 'Vista de Producto'), ('agregar_carrito', 'Agregado al Carrito'), ('remover_carrito', 'Removido del Carrito'), ('inicio_checkout', 'Inicio de Checkout'), ('compra_completada', 'Compra Completada'), ('busqueda', 'Búsqueda'), ('registro', 'Registro de Usuario'), ('login', 'Inicio de Sesión')], max_length=50)),
                ('valor_monetario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor asociado al evento (ej: monto de compra)', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='catalogo.categoria')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='pedidos.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Usuario',
                'verbose_name_plural': 'Eventos de Usuario',
                'db_table': 'analytics_eventos_usuario',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo_evento', '-timestamp'], name='analytics_e_tipo_ev_d0a2a8_idx'), models.Index(fields=['usuario', '-timestamp'], name='analytics_e_usuario_41a606_idx'), models.Index(fields=['producto', '-timestamp'], name='analytics_e_product_4d6683_idx')],
            },
        ),
    ]
